trigger:
  branches:
    include:
      - master


pool: default

stages:
  - stage: stageinfrapipeline
    displayName: vineet infra rg
    jobs:
      - job: terraforminstall
        displayName: infrainit job
        steps:
          - 
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest' 
    
- task: TerraformTaskV5@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm:'azuresc'
      backendAzureRmResourceGroupeName:'my-rg'
      backendAzureRmStorageAccountName:'vineet271991vineet'
      backendAzureRmContainename: 'vinni'
      backendAzurermKey: 'ra,.terraform.tfstate'
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: 'Azuresc'
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'apply'
      commandOptions: '-auto -approve'
      environmentServiceAnmeAzureRM: 'Azuresc'
